### ISSUE TITLE
Error: "tried to access field processing.core.PFont.size from class code_swarm"

### ISSUE THREAD

**Issue by caseywatts** [rictic/code_swarm#17]
I'm running OS X 10.10.2, I've upgraded and migrated my development files through a few computers.

When I ran code_swarm (after some other troubleshooting) I got this error:

```
Exception in thread "Animation Thread" java.lang.IllegalAccessError: tried to access field processing.core.PFont.size from class code_swarm
    at code_swarm.drawLegend(code_swarm.java:537)
    at code_swarm.draw(code_swarm.java:426)
    at processing.core.PApplet.handleDraw(PApplet.java:2306)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)
    at processing.core.PApplet.run(PApplet.java:2177)
    at java.lang.Thread.run(Thread.java:695)
```

I've determined that this is probably pointing at a call to the function [`font.getSize()`](https://github.com/rictic/code_swarm/search?utf8=%E2%9C%93&q=font.getSize%28%29&type=Code).

The last time this was edited was in pull request #14 by @longbai. When I checked out commit `70867b3a` and tried it, everything works again! I don't know enough java to troubleshoot this any further on my own. I'm happy to provide more information about my programming environment if that would help!

**Comment by longbai** [comment]
the processing library has updated and do not allow access the field directly. please use getSize.
