### ISSUE TITLE
CircularAvatars requires exact pixel size

### ISSUE THREAD

**Issue by schwern** [rictic/code_swarm#4]
Using CircularAvatars and a 1x1 black default.png (to make it effectively invisible) I got:

Exception in thread "Animation Thread" java.lang.RuntimeException: The PImage used with mask() must be the same size as the applet.
    at processing.core.PImage.mask(PImage.java:599)
    at processing.core.PImage.mask(PImage.java:614)
    at code_swarm$PersonNode.<init>(code_swarm.java:1503)
    at code_swarm.update(code_swarm.java:740)
    at code_swarm.draw(code_swarm.java:382)
    at processing.core.PApplet.handleDraw(PApplet.java:1395)
    at processing.core.PApplet.run(PApplet.java:1300)
    at java.lang.Thread.run(Thread.java:637)

It would be nice if CircularAvatars did not restrict the avatar size.

**Comment by dwo** [comment]
Do you know what the exact pixel size is? I get this when I set the config to LocalAvatars, even if I only leave the provided default.png in there.

**Comment by schwern** [comment]
It's been so long, I don't remember any details.  Sorry.
