### ISSUE TITLE
Invalid Argument error

### ISSUE THREAD

**Issue by ttback** [rictic/code_swarm#9]
I have all the env ready for ant, ruby, python 2.7.1 on Mac, but I can't get this code_swarm command to run even on code_swarm repo itself. Not sure why. I tried to manually generate activity.log file through 
`git log --name-status --pretty=format:'%n--------------------------%nr%h | %ae | %ai (%aD) |
 x lines%nChanged paths:' > activity.log`
But convert_logs.py can't convert that into event.xml
I'm not sure what's going on. 

**Error:**

```
Creating default config file at /path/to/code_swarm/bin/code_swarm/.code_swarm/project.config
Traceback (most recent call last):
  File "/path/to/code_swarm/bin/code_swarm", line 245, in <module>
    main()
  File "/path/to/code_swarm/bin/code_swarm", line 76, in main
    proj_cfg = autogenerate_files(options)
  File "/path/to/code_swarm/bin/code_swarm", line 181, in autogenerate_files
    cp_tpl = os.path.join(root_path(), "bin", "config.template")
  File "/path/to/code_swarm/bin/code_swarm", line 99, in root_path
    real_path = os.path.join(os.path.dirname(__file__), os.readlink(__file__))
OSError: [Errno 22] Invalid argument: '/path/to/code_swarm/bin/code_swarm'
```

**Comment by ttback** [comment]
Resolved, the root cause was in the parsed xml format in my git log command. Missed a few --'s

**Comment by bitcoiners** [comment]
Hello,
I am having this same issue and I have pulled the latest source code for code_swarm..

**Comment by bitcoiners** [comment]
~/dev/projects/bitcoin(master) $ code_swarm -r
Creating default config file at /home/slava/dev/projects/bitcoin/.code_swarm/project.config
Traceback (most recent call last):
  File "/home/slava/dev/projects/code_swarm/bin/code_swarm", line 245, in <module>
    main()
  File "/home/slava/dev/projects/code_swarm/bin/code_swarm", line 76, in main
    proj_cfg = autogenerate_files(options)
  File "/home/slava/dev/projects/code_swarm/bin/code_swarm", line 181, in autogenerate_files
    cp_tpl = os.path.join(root_path(), "bin", "config.template")
  File "/home/slava/dev/projects/code_swarm/bin/code_swarm", line 99, in root_path
    real_path = os.path.join(os.path.dirname(**file**), os.readlink(**file**))
OSError: [Errno 22] Invalid argument: '/home/slava/dev/projects/code_swarm/bin/code_swarm'

**Comment by rubytastic** [comment]
same issue here on latest OSX, 
any way to fix this?

**Comment by rubytastic** [comment]
Creating default config file at /git/project/.code_swarm/project.config
Traceback (most recent call last):
  File "/src/code_swarm/bin/code_swarm", line 245, in <module>
    main()
  File "/src/code_swarm/bin/code_swarm", line 76, in main
    proj_cfg = autogenerate_files(options)
  File "/src/code_swarm/bin/code_swarm", line 181, in autogenerate_files
    cp_tpl = os.path.join(root_path(), "bin", "config.template")
  File "/src/code_swarm/bin/code_swarm", line 99, in root_path
    real_path = os.path.join(os.path.dirname(**file**), os.readlink(**file**))
OSError: [Errno 22] Invalid argument: '/src/code_swarm/bin/code_swarm'

**Comment by holzman** [comment]
Check my holzman/code_swarm bug9 branch -- this looks like a simple fix.
(I'm not optimistic of a pull request happening to rictic, my last pr is still waiting after 10 months..)
